[package]
name = "livesplit-core"
version = "0.9.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
documentation = "https://docs.rs/livesplit-core/"
repository = "https://github.com/LiveSplit/livesplit-core"
license = "Apache-2.0/MIT"
description = "livesplit-core is a library that provides a lot of functionality for creating a speedrun timer."
readme = "README.md"
keywords = ["speedrun", "timer", "livesplit"]
include = [
    "src/*",
    "Cargo.toml",
    "LICENSE-APACHE",
    "LICENSE-MIT",
    "CODE_OF_CONDUCT.md",
    "README.md"
]

[badges]
travis-ci = { repository = "LiveSplit/livesplit-core" }
appveyor = { repository = "CryZe/livesplit-core" }

[profile.release]
lto = true
panic = "abort"

[workspace]
members = ["capi", "capi/bind_gen", "capi/js", "capi/staticlib", "capi/cdylib", "capi/python"]

[dependencies]
base64 = "0.9.0"
byteorder = "1.2.1"
derive_more = "0.7.0"
image = { version = "0.18.0", features = ["png_codec"], default-features = false }
indexmap = { version = "0.4.1", default-features = false }
livesplit-hotkey = { path = "hotkey", version = "0.3.0" }
odds = { version = "0.3.1", features = ["std-vec"], default-features = false }
ordered-float = "0.5.0"
palette = { version = "0.3.0", default-features = false }
parking_lot = { version = "0.5.3", default-features = false }
quick-error = "1.2.0"
quick-xml = "0.11.0"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
unicase = "2.1.0"

[target.'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))'.dependencies]
# Blocked by chrono's time dependency
# https://github.com/chronotope/chrono/pull/137
chrono = { version = "0.4.0", features = ["serde"], default-features = false }
